source 'https://rubygems.org'

gem 'pg', '~> 0.18'
gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-activerecord'
gem 'activerecord'
gem 'sinatra-contrib'
gem 'rake'
gem 'csv'
gem 'redis'
gem 'polylines'
gem 'pry'
gem 'faraday'

group :development, :test do
  gem 'capybara', '~> 3.0.3'
  gem 'database_cleaner'
  gem 'shoulda-matchers'
  gem 'launchy'
  gem 'rack-test'
  gem 'rspec'
  gem 'shotgun'
  gem 'tux'
  gem 'factory_bot'
end
